### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [happycod3r/fzf-tools#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by happycod3r** [comment]
Adding sorry for taking long :) Please do that would be awesome!

**Comment by unixorn** [comment]
Thanks, merged it into the list

**Comment by happycod3r** [comment]
Thank YOU, and anytime!
